CCC		 = g++ -std=c++11
CCFLAGS  = -L/sw/gcc-${GCC4__V}/lib -static-liibstdc++

# Default-målet är clean. Lägg till alla tester som specifika mål.

clean:
	@ \rm -rf *.o *.gch

CardContainerManagerTest: CardContainerManagerTest.cc 
	$(CCC) 